# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FCE++' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FCE++
pod 'Parse'
pod 'SVProgressHUD'
pod 'RSSelectionMenu', :git => 'https://github.com/samflattery/RSSelectionMenu/', :commit => '27d67f9a58d81e4e59b4f7c651b7128860fcf6d8'
pod 'Cosmos'
pod 'TimeIntervals'

end
