# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FCE++' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FCE++
pod 'Parse'
pod 'SVProgressHUD'
pod 'RSSelectionMenu'

end
